Entity/Diseases.php
<?php

namespace CMS\HospitalsBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;

/**
 * Diseases
 */
class Diseases
{
    /**
     * @var integer
     */
    private $id;

    /**
     * @var string
     */
    private $title;

    /**
     * @var \DateTime
     */
    private $date_create;

    /**
     * @var \DateTime
     */
    private $date_update;

    /**
     * @var integer
     */
    private $create_by;

    /**
     * @var integer
     */
    private $update_by;

    /**
     * @var ArrayCollection
     */
    private $hospitals;

    public function __construct()
    {
        $this->hospitals = new ArrayCollection();
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set title
     *
     * @param string $title
     * @return Services
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * @return ArrayCollection
     */
    public function getHospitals()
    {
        return $this->hospitals;
    }

    /**
     * @param ArrayCollection $hospitals
     * @return $this
     */
    public function setHospitals($hospitals)
    {
        $this->hospitals = $hospitals;

        return $this;
    }

    /**
     * @return int
     */
    public function getCreateBy()
    {
        return $this->create_by;
    }

    /**
     * @param int $create_by
     * @return $this
     */
    public function setCreateBy($create_by)
    {
        $this->create_by = $create_by;

        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getDateCreate()
    {
        return $this->date_create;
    }

    /**
     * @param \DateTime $date_create
     * @return $this
     */
    public function setDateCreate($date_create)
    {
        $this->date_create = new \DateTime();

        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getDateUpdate()
    {
        return $this->date_update;
    }

    /**
     * @param \DateTime $date_update
     * @return $this
     */
    public function setDateUpdate($date_update)
    {
        $this->date_update = new \DateTime();

        return $this;
    }

    /**
     * @return int
     */
    public function getUpdateBy()
    {
        return $this->update_by;
    }

    /**
     * @param int $update_by
     * @return $this
     */
    public function setUpdateBy($update_by)
    {
        $this->update_by = $update_by;

        return $this;
    }
}

Form/DiseasesType.php
<?php

namespace CMS\HospitalsBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class DiseasesType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', 'cms_localization_text_type');
    }

    /**
     * Configures the options for this type.
     *
     * @param OptionsResolver $resolver The resolver for the options.
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'CMS\HospitalsBundle\Entity\Diseases'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'cms_hospitalsbundle_diseases';
    }
}

Controller/DiseasesController.php
<?php
/**
 * Created by PhpStorm.
 * User: pavel
 * Date: 25.02.16
 * Time: 11:38
 */

namespace CMS\HospitalsBundle\Controller;


use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

class DiseasesController extends Controller
{
    /**
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function listAction()
    {
        $service = $this->get('cms.hospitals.diseases.service');

        return $this->render('HospitalsBundle:Diseases:list.html.twig', array(
            'diseases' => $service->findAll()
        ));
    }

    /**
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function createAction(Request $request)
    {
        $service = $this->get('cms.hospitals.diseases.service');

        $form = $service->generateForm();

        if ($request->isMethod('POST')) {
            $form->handleRequest($request);

            if ($form->isValid()) {
                $service->update($form->getData());

                return $this->redirect($this->generateUrl('cms_hospitals_diseases_list'));
            }
        }

        return $this->render('HospitalsBundle:Diseases:edit.html.twig', array(
            'form' => $form->createView()
        ));
    }

    /**
     * @param Request $request
     * @param $id
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function editAction(Request $request, $id)
    {
        $service = $this->get('cms.hospitals.diseases.service');

        $form = $service->generateForm($service->findOneById($id));

        if ($request->isMethod('POST')) {
            $form->handleRequest($request);

            if ($form->isValid()) {
                $service->update($form->getData());

                return $this->redirect($this->generateUrl('cms_hospitals_diseases_list'));
            }
        }

        return $this->render('HospitalsBundle:Diseases:edit.html.twig', array(
            'form' => $form->createView()
        ));
    }

    /**
     * @param $id
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function deleteAction($id)
    {
        $service = $this->get('cms.hospitals.diseases.service');

        $service->delete($id);

        return $this->redirect($this->generateUrl('cms_hospitals_diseases_list'));
    }
}

Resources/views/Diseases/edit.html.twig
{% extends 'DashboardBundle:Layout:base.html.twig' %}

{% block javascripts %}
    {{ parent() }}
    {% javascripts
    'bundles/localization/js/localization_form.js' %}
    <script type="text/javascript" src="{{ asset_url }}"></script>
    {% endjavascripts %}
{% endblock %}

{% block body %}
    {% embed "HospitalsBundle::main.html.twig" %}
        {% block main %}
            <div class="row">
                {% form_theme form 'HospitalsBundle::fields.html.twig' %}
                <div class="col-md-12">
                    {{ show_locale_tabs() }}
                    <br/>

                    <form method="post" {{ form_enctype(form) }} class="form-horizontal">
                        <div class="row">
                            <div class="col-md-12">
                                {{ form_errors(form) }}
                                {{ form_row(form.title,{
                                    'label': 'Title'|trans({},'labels'),
                                }) }}
                                {{ form_rest(form) }}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="well well-sm text-right">
                                    <input type="submit" class="btn btn-primary btn-sm" data-loading-text="Saving..."
                                           value="{{ 'Save'|trans({}, 'systems') }}"/>
                                    <a href="javascript:history.go(-1)"
                                       class="btn btn-default btn-sm">{{ 'Cancel'|trans({}, 'systems') }}</a>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        {% endblock %}
    {% endembed %}
{% endblock %}

Resources/views/Diseases/list.html.twig
{% extends 'DashboardBundle:Layout:base.html.twig' %}

{% block body %}
    {% embed 'HospitalsBundle::main.html.twig' %}
        {% block panelButtons %}
            <a href="{{ url('cms_hospitals_diseases_create') }}"
               class="glyphicon glyphicon-plus btn btn-success btn-xs">{{ 'Add'|trans }}</a>
        {% endblock %}

        {% block main %}
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                    <th><input type="checkbox" data-action="selectAll"/></th>
                    <th>ID</th>
                    <th>{{ 'Title'|trans }}</th>
                    <th>{{ 'Create by'|trans }}</th>
                    <th>{{ 'Date'|trans }}</th>
                    <th></th>
                    <th></th>
                    </thead>
                    <tbody>
                    {% for disease in diseases %}
                        <tr>
                            <td><input type="checkbox" value="{{ disease.id }}" name="mark[]"/></td>
                            <td>{{ disease.id }}</td>
                            <td>
                                <a href="{{ url('cms_hospitals_diseases_edit', {id: disease.id}) }}">
                                    {{ disease.title|locale }}
                                </a>
                            </td>
                            <td>{{ disease.createBy }}</td>
                            <td>{{ disease.dateCreate|date('d.m.Y') }}</td>
                            <td><a href='{{ url('cms_hospitals_diseases_edit', {id: disease.id}) }}'><span
                                            class="glyphicon lead text-primary glyphicon-pencil"></span></a></td>
                            <td><a href='{{ url('cms_hospitals_diseases_delete', {id: disease.id}) }}'><span
                                            class="glyphicon lead text-danger glyphicon-remove-circle"></span></a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        {% endblock %}
    {% endembed %}
{% endblock %}